//
// Generated file, do not edit! Created by opp_msgtool 6.0 from spaningtree.msg.
//

#ifndef __SPANINGTREE_M_H
#define __SPANINGTREE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SpanTree;
/**
 * Class generated from <tt>spaningtree.msg:16</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message SpanTree
 * {
 *     int source_id;
 *     int hopCount = 0;
 *     int root_id;
 *     int root_port;
 * }
 * </pre>
 */
class SpanTree : public ::omnetpp::cMessage
{
  protected:
    int source_id = 0;
    int hopCount = 0;
    int root_id = 0;
    int root_port = 0;

  private:
    void copy(const SpanTree& other);

  protected:
    bool operator==(const SpanTree&) = delete;

  public:
    SpanTree(const char *name=nullptr, short kind=0);
    SpanTree(const SpanTree& other);
    virtual ~SpanTree();
    SpanTree& operator=(const SpanTree& other);
    virtual SpanTree *dup() const override {return new SpanTree(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource_id() const;
    virtual void setSource_id(int source_id);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual int getRoot_id() const;
    virtual void setRoot_id(int root_id);

    virtual int getRoot_port() const;
    virtual void setRoot_port(int root_port);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SpanTree& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SpanTree& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SpanTree *fromAnyPtr(any_ptr ptr) { return check_and_cast<SpanTree*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SPANINGTREE_M_H

